name: Sync Markdown to HackMD

on:
  push:
    paths:
      - 'docs/**/*.md'

jobs:
  sync-to-hackmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 或 '16'，都可以

      - name: Install hackmd-cli
        run: |
          npm install -g hackmd-cli

      - name: Sync README to HackMD
        env:
          HACKMD_API_TOKEN: ${{ secrets.HACKMD_API_TOKEN }}
          HACKMD_NOTE_ID: ${{ secrets.HACKMD_NOTE_ID }}
        run: |
          hackmd-cli upload-note \
            --note-id "$HACKMD_NOTE_ID" \
            --token "$HACKMD_API_TOKEN" \
            --file "docs/README.md"
