name: Sync Markdown to HackMD

on:
  push:
    paths:
      - 'docs/**/*.md'

jobs:
  sync-to-hackmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync README.md to HackMD
        env:
          HACKMD_API_TOKEN: ${{ secrets.HACKMD_API_TOKEN }}
          HACKMD_NOTE_ID: ${{ secrets.HACKMD_NOTE_ID }}
        run: |
          curl --request PATCH \
            --url https://api.hackmd.io/v1/notes/$HACKMD_NOTE_ID \
            --header "Authorization: Bearer $HACKMD_API_TOKEN" \
            --header "Content-Type: text/plain" \
            --data-binary "@docs/README.md"
